### ISSUE TITLE
docker build error for pi_myhero_spark

### ISSUE THREAD

**Issue by scottjester** [juliogomez/devops#4] opened 2022-06-26 14:28 UTC
sjester@primarypi:~/myhero_spark $ docker build -t configt/pi_myhero_spark .
Sending build context to Docker daemon    105kB
Step 1/9 : FROM alpine
 ---> 6e30ab57aeee
Step 2/9 : MAINTAINER Julio Gomez <jgomez2@cisco.com>
 ---> Using cache
 ---> 88e005656b04
Step 3/9 : EXPOSE 5000
 ---> Using cache
 ---> 57666edc792b
Step 4/9 : RUN apk add -U         python         py-pip         ca-certificates   && rm -rf /var/cache/apk/*   && pip install --no-cache-dir           setuptools           wheel
 ---> Running in 3bfd0436a3c1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]

**Comment by juliogomez** [comment] 2022-06-27 13:54
The problem is in the latest alpine version, solved by specifying alpine:3.11 in the Dockerfile. Fixed now, thanks for the heads up!

**Closed as completed by juliogomez** 2022-06-27 13:54 UTC
